### ISSUE TITLE
Job listing page. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#123]
The user will be able to navigate to a job listing page, with mock posts of jobs. 

Story points: 2,
Priority: Low,
Risk: Low

- [x] Ability to navigate to a job posting page, [#134]
- [x] Ability to post new job postings, [#151]
- [x] Only Job accounts should post jobs [#152]
- [x] External User profile accounts that can be viewed by anyone [#161]

**Comment by PWatine** [comment]
![123](https://user-images.githubusercontent.com/35372462/37807669-04cd21aa-2e1d-11e8-8569-a57520aa6d05.png)
Test completed.

**Comment by PWatine** [comment]
![123](https://user-images.githubusercontent.com/35372462/37808429-b356ac0c-2e20-11e8-8e9d-21dbd256a440.png)
Test completed.

**Comment by dfeokti** [comment]
Closed, passed acceptance testing above.
