### ISSUE TITLE
Individual question page.

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#45]
This user will be provided with a detailed individual question page, where they will be able to submit an answer. The user will also be able to upvote or downvote any answers on the page. Additionally, the submitter of the question will be able to mark an answer as "accepted or rejected."

**Story points: 2,
Priority: Medium,
Risk: Low**

- [x] Ability to submit an answer, 1 hour [#58]
- [x] Ability to accept or reject an answer. 1 hour [#59] 
- [x] Detailed question information (username of the poster, date submitted, current score), 1 hour [#60]
- [x] Ability to upvote or downvote an answer, 1 hour [#61]

**Comment by Michael-Gagnon** [comment]
As I mentioned in the pull request, the front end features are done as of now.

**Comment by PWatine** [comment]
The test has been constructed and done.
![45](https://user-images.githubusercontent.com/35372462/37078073-b7ac3578-21ab-11e8-8c67-fcc229906111.png)

**Comment by dfeokti** [comment]
Issues 5,6,7 resolved. Questions can now be clicked, upvoted or downvoted. 
13,14 to be reopened for Sprint 4.

**Comment by PWatine** [comment]
![45](https://user-images.githubusercontent.com/35372462/37730028-f664359e-2d14-11e8-9c3c-90603608f982.png)
Test done. Will create a bug report shortly.

**Comment by dfeokti** [comment]
As [#173}, issue 15 cannot be reproduced, so the acceptance test is considered completed.
