### ISSUE TITLE
Back-end login functionality. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#85]
**Story points: 2,
Priority: Medium,
Risk: Low**

The user will be able to type in a user name and password to log in, and have the credentials verified by the server. 

- [x] Ability to log in, using correct credentials, 3 hours. [#93]
- [x] Feedback on erroneous login/register, 2 hours. [#93]
- [x] Persistent feedback of logged in status. 3 hours [#94] @

**Comment by PWatine** [comment]
![85](https://user-images.githubusercontent.com/35372462/37132382-72bfb6c8-225b-11e8-89e5-934b202d44a2.png)
Test completed.

**Comment by dfeokti** [comment]
To be reopened in Sprint 4, along with final cleanup.

**Comment by PWatine** [comment]
![85](https://user-images.githubusercontent.com/35372462/37694180-84862ef6-2c9b-11e8-9c1d-f0eac3ccc1d0.png)
New test completed.

**Comment by dfeokti** [comment]
Tests passed, the user is informed that they can logout through the header.
