### ISSUE TITLE
Front-end user page functionality. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#88]
**Story points: 3,
Priority: Medium,
Risk: Low**

The user will be able to view the profile page, check relevant interests, languages or frameworks.

- [x] Add a button in the nav bar to navigate to the user page [#111]

**User page 5 hours.**
- [x] Profile picture and banner visible at the top of the user page. 1 hour.  [#100]
- [x] Display "Contact me" section (email address, github, linkedin, phone number, etc). 1 hour. [#106]
- [x] Display "About me" section (name, birthday, gender, age, etc). 1 hour. [#107]
- [x] User posted questions as a sorted list with answered questions at the top. 1 hour. [#109]
- [x] User posted answers as a sorted list with accepted answers at the top. 1 hour. [#110]
______________________________________________________
**Edit user page 5 hours**
- [x] Edit profile picture among a set of 5 standard images. 1 hour.   [#101]
- [x] Edit banner color using color picker. 1 hour.   [#105]
- [x] Edit "contact me" section containing text fields for contacting user. 1 hour.   [#108]
- [x] Edit "about me" section containing text fields regard user info. 1 hour.  [#112]

**Comment by vineetkoppalkar** [comment]
@BarsemianGeorgik Would you happen know why the submit button in 'edituserpage.hbs' is not redirecting to the 'userpage.hbs' despite the fact that it loads "localhost:3000/userpage?

**Comment by BarsemianGeorgik** [comment]
@vineetkoppalkar  By definition the form tag contained inside the edit user page file, the file doesn't have a particular code on the server side to handle its submit request, therefore i removed for now the ability to send the post request until the backend side of the file is ready to handle it and only then will the submit button guide the user back to the user profile page

**Comment by kjanei** [comment]
All front-end functionality has been implemented by the pull requests listed above.

**Comment by dfeokti** [comment]
Reopened, to work on failed tests.

**Comment by dfeokti** [comment]
Password change will not be implemented.

**Comment by PWatine** [comment]
![88](https://user-images.githubusercontent.com/35372462/37748453-4e1272b6-2d5a-11e8-8b51-2db22713c2a7.png)
![88 2](https://user-images.githubusercontent.com/35372462/37748458-51d56da4-2d5a-11e8-8678-878dfff5a06d.png)
Test completed.

**Comment by dfeokti** [comment]
Acceptance test passed, password change will not be implemented as above.
